FROM php:8.2-cli
RUN apt-get update && apt-get install -y git unzip libzip-dev \
 && docker-php-ext-install zip \
 && pecl install pcov \
 && docker-php-ext-enable pcov \
 && rm -rf /var/lib/apt/lists/*
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
WORKDIR /app
